application: helloworld
version: 1
runtime: go
api_version: go1

default_expiration: "1s"

handlers:
- url: /admin/.*
  script: _go_app
  login: admin
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /.*
  script: _go_app
